# Generated by Django 4.0.6 on 2022-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_data',
            new_name='book_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='book_hour',
            field=models.TextField(null=True),
        ),
    ]
