# Generated by Django 4.0.6 on 2022-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_calendardate_delete_date_alter_booking_book_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='date',
            field=models.TextField(),
        ),
    ]
