# Generated by Django 4.0.6 on 2022-09-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_booking_book_date_alter_calendardate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendardate',
            name='date',
            field=models.DateField(),
        ),
    ]
