# Generated by Django 4.0.6 on 2022-09-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_calendardate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='index_of_hour_in_work_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
