# Generated by Django 4.0.6 on 2022-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_booking_index_of_hour_in_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='index_of_hour_in_work_hours',
            field=models.IntegerField(null=True),
        ),
    ]
