# Generated by Django 4.0.6 on 2022-09-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_booking_index_of_hour_in_work_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='index_of_hour_in_work_hours',
        ),
    ]
