# Generated by Django 4.0.6 on 2022-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='id',
        ),
        migrations.AddField(
            model_name='photos',
            name='d',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
